// export const UserTypes = {
//   RealEstateAgent: "RealEstateAgent",
//   SolarRep: "SolarRep",
//   SalesDevRep: "SalesDevRep",
//   MarketerAgent: "MarketerAgent",
//   WebsiteAgent: "WebsiteAgent",
//   InsuranceAgent: "InsuranceAgent",
//   RecruiterAgent: "RecruiterAgent",
//   TaxAgent: "TaxAgent",
//   DebtCollectorAgent: "DebtCollectorAgent",
//   MedSpaAgent: "MedSpaAgent",
//   LoanOfficerAgent: "LoanOfficerAgent",
//   LawAgent: "LawAgent",
// };

export const UserTypes = {
  RealEstateAgent: 'RealEstateAgent',
  SolarRep: 'SolarRep',
  General: 'GeneralAgent',
  Reception: 'ReceptionAgent',
  SalesDevRep: 'SalesDevRep',
  MarketerAgent: 'MarketerAgent',
  WebsiteAgent: 'WebsiteAgent',
  InsuranceAgent: 'InsuranceAgent',
  RecruiterAgent: 'RecruiterAgent',
  TaxAgent: 'TaxAgent',
  DebtCollectorAgent: 'DebtCollectorAgent',
  MedSpaAgent: 'MedSpaAgent',
  LoanOfficerAgent: 'LoanOfficerAgent',
  LawAgent: 'LawAgent',
  Admin: 'admin',
  Creator: 'Creator',
}
