const BasePath = "https://www.blindcircle.com/agentx/"

const Apis = {
    register: `${BasePath}api/user/register`,
    LogIn: `${BasePath}api/user/login`,
    defaultData: `${BasePath}api/data/loadDefaualtData`,
    buildAgent: `${BasePath}api/agent/buildAgent`,
    DelAgent: `${BasePath}api/agent/deleteAgent`,
    findPhoneNumber: `${BasePath}api/agent/findPhoneNumbers`,
    purchaseNumber: `${BasePath}api/agent/purchasePhone`,
    userAvailablePhoneNumber: `${BasePath}api/agent/listUsersAvailablePhoneNumbers`,
    reassignNumber: `${BasePath}api/agent/releasePhoneNumber`,
    asignPhoneNumber: `${BasePath}api/agent/assignPhoneNumber`,
    addKyc: `${BasePath}api/agent/addKyc`,
    getVoices: "https://fine-tuner.ai/api/1.1/wf/v2_voice_agent_voices",
    getKYCs: `${BasePath}api/agent/getKycs`,
    getPipelines: `${BasePath}api/pipeline/getPipelines`,
    updatePipeline: `${BasePath}api/pipeline/updatePipeline`,
    createPipeLineCadence: `${BasePath}api/pipeline/createPipelineCadence`,
    deletePipeline: `${BasePath}api/pipeline/deletePipeline`,
    updateAgent: `${BasePath}api/agent/updateAgent`,
    createLead: `${BasePath}api/leads/addLeads`,
    getLeads: `${BasePath}api/leads/getLeads`,
    getSheets: `${BasePath}api/leads/getSheets`,
    getAgents: `${BasePath}api/agent/getAgents`,
    assignLeadToPipeLine: `${BasePath}api/pipeline/assignLeadsToPipeline`,
    uniqueColumns: `${BasePath}api/leads/getUniqueColumns`,
    CheckEmail: `${BasePath}api/user/checkEmailExists`,
    CheckPhone: `${BasePath}api/user/checkPhoneNumber`,
    getCallLogs: `${BasePath}api/leads/callLogs`,
    getSheduledCallLogs: `${BasePath}api/pipeline/getScheduledCalls`,
    getAgentCallLogs: `${BasePath}api/agent/getAgentCallActivity`,
    pauseAgent: `${BasePath}api/pipeline/pauseAgentCadence`,
    getUniqueColumns: `${BasePath}api/leads/getUniqueColumns`,
    addSmartList: `${BasePath}api/leads/addSmartList`,
    delSmartList: `${BasePath}api/leads/deleteList`,
    addCustomStage: `${BasePath}api/pipeline/createStage`,
    deleteStage: `${BasePath}api/pipeline/deletePipelineStage`,
    UpdateStage: `${BasePath}api/pipeline/updateStage`,
    addObjectionGuardrial: `${BasePath}api/agent/addObjectionGuardRail`,
    getObjectionGuardrial: `${BasePath}api/agent/getObjectionsAndGuardrails`,
    reorderStages: `${BasePath}api/pipeline/reorderStages`,
    createPipeLine: `${BasePath}api/pipeline/createPipeline`,
    testAI: `${BasePath}api/agent/testAi`

}

export default Apis
